import sys
import os
import json
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from dtl_algebra import generate_dtl_states, apply_E_i
import sympy

def check_irreducibility(L, j):
    states = generate_dtl_states(L, j)
    q = sympy.Symbol('q')

    # Group states by p (number of zeros)
    p_groups = {}
    for i, s in enumerate(states):
        p = s.count(0)
        if p not in p_groups:
            p_groups[p] = []
        p_groups[p].append((i, s))

    results = {}

    print(f"==================================================")
    print(f"Irreducibility Check for L={L}, j={j}")
    print(f"Total States: {len(states)}")
    print(f"==================================================\n")

    for p, group in sorted(p_groups.items(), reverse=True): # highest p first
        print(f"--- Subspace V^{{L={L},j={j},p={p}}} ({len(group)} states) ---")

        # Build adjacency matrix inside this subspace
        # Edge A -> B exists if any E_i |A> contains |B> with non-zero coefficient
        dim_sub = len(group)
        adj = [[] for _ in range(dim_sub)]

        # Mapping from global state tuple back to local index in this group
        state_to_local_idx = {s: local_idx for local_idx, (_, s) in enumerate(group)}

        for local_idx, (global_idx, state) in enumerate(group):
            # Apply all E_i generators
            for i in range(L - 1):
                res = apply_E_i(state, i, q)
                for res_state, weight in res:
                    if res_state in state_to_local_idx:
                        target_local_idx = state_to_local_idx[res_state]
                        if weight != 0 and target_local_idx not in adj[local_idx]:
                            adj[local_idx].append(target_local_idx)

        # Now we check if this directed graph is strongly connected.
        # If it is strongly connected, the module is irreducible under the algebra generated by {E_i}.
        # We can use Tarjan's or Kosaraju's algorithm, or since graphs are small, a simple BFS from every node.
        is_strongly_connected = True
        for start_node in range(dim_sub):
            visited = [False] * dim_sub
            queue = [start_node]
            visited[start_node] = True
            count = 1

            while queue:
                curr = queue.pop(0)
                for neighbor in adj[curr]:
                    if not visited[neighbor]:
                        visited[neighbor] = True
                        queue.append(neighbor)
                        count += 1

            if count < dim_sub:
                is_strongly_connected = False
                break

        if dim_sub == 0:
            is_strongly_connected = True

        print(f"  Is Strongly Connected (Irreducible)? : {is_strongly_connected}\n")

        results[f"p={p}"] = {
            "num_states": dim_sub,
            "is_irreducible": is_strongly_connected,
            "states": [str(s) for _, s in group]
        }

    return results

if __name__ == "__main__":
    L = 10
    j = 4
    if len(sys.argv) > 2:
        L = int(sys.argv[1])
        j = int(sys.argv[2])

    res = check_irreducibility(L, j)

    # Save to JSON
    os.makedirs("experiment_outputs", exist_ok=True)
    out_path = f"experiment_outputs/irreducibility_L{L}_j{j}.json"
    with open(out_path, "w") as f:
        json.dump(res, f, indent=2)
    print(f"Saved irreducibility check to {out_path}")
